"""sync_model_columns_to_schema

Revision ID: bf9bb1b20762
Revises: d1e2f3a4b5c6
Create Date: 2026-02-24 22:27:53.101178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bf9bb1b20762'
down_revision: Union[str, None] = 'd1e2f3a4b5c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_customdomains_domain'), table_name='customdomains')
    op.drop_index(op.f('ix_customdomains_id'), table_name='customdomains')
    op.drop_index(op.f('ix_customdomains_tenant_id'), table_name='customdomains')
    op.drop_table('customdomains')
    op.drop_index(op.f('ix_tenant_sso_configs_id'), table_name='tenant_sso_configs')
    op.drop_index(op.f('ix_tenant_sso_configs_tenant_id'), table_name='tenant_sso_configs')
    op.drop_table('tenant_sso_configs')
    op.add_column('documentchunks', sa.Column('vector_id', sa.String(), nullable=True))
    op.drop_index(op.f('ix_documentchunks_tenant_embedding'), table_name='documentchunks', postgresql_where='(embedding IS NOT NULL)')
    op.alter_column('documents', 'file_size',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('documents', 'quality_report',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_column('documents', 'checksum')
    op.drop_column('documents', 'page_count')
    op.drop_column('documents', 'mime_type')
    op.drop_column('documents', 'lang')
    op.drop_column('tenants', 'contact_name')
    op.drop_column('tenants', 'contact_phone')
    op.drop_column('tenants', 'tax_id')
    op.drop_column('tenants', 'brand_name')
    op.drop_column('tenants', 'contact_email')
    op.drop_column('tenants', 'brand_logo_url')
    op.drop_column('tenants', 'brand_primary_color')
    op.drop_column('tenants', 'custom_domain')
    op.drop_column('tenants', 'brand_favicon_url')
    op.drop_column('tenants', 'data_residency_note')
    op.drop_column('tenants', 'brand_secondary_color')
    op.drop_column('tenants', 'region')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('region', sa.VARCHAR(length=10), server_default=sa.text("'ap'::character varying"), autoincrement=False, nullable=False))
    op.add_column('tenants', sa.Column('brand_secondary_color', sa.VARCHAR(length=7), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('data_residency_note', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('brand_favicon_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('custom_domain', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('brand_primary_color', sa.VARCHAR(length=7), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('brand_logo_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('contact_email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('brand_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('tax_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('contact_phone', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('contact_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('lang', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('mime_type', sa.VARCHAR(length=200), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('page_count', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('documents', sa.Column('checksum', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.alter_column('documents', 'quality_report',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('documents', 'file_size',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.create_index(op.f('ix_documentchunks_tenant_embedding'), 'documentchunks', ['tenant_id'], unique=False, postgresql_where='(embedding IS NOT NULL)')
    op.drop_column('documentchunks', 'vector_id')
    op.create_table('tenant_sso_configs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('provider', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('client_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('client_secret', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('enabled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('allowed_domains', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('auto_create_user', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('default_role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('tenant_sso_configs_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('tenant_sso_configs_pkey')),
    sa.UniqueConstraint('tenant_id', 'provider', name=op.f('uq_tenant_provider'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_tenant_sso_configs_tenant_id'), 'tenant_sso_configs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_sso_configs_id'), 'tenant_sso_configs', ['id'], unique=False)
    op.create_table('customdomains',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('domain', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('verification_token', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('ssl_provisioned', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('customdomains_tenant_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('customdomains_pkey')),
    sa.UniqueConstraint('domain', name=op.f('uq_customdomains_domain'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_customdomains_tenant_id'), 'customdomains', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_customdomains_id'), 'customdomains', ['id'], unique=False)
    op.create_index(op.f('ix_customdomains_domain'), 'customdomains', ['domain'], unique=False)
    # ### end Alembic commands ###
